const ScraperBase = require('../core/ScraperBase');
const { BrowserWindow, app } = require('electron');
const path = require('path');
const fs = require('fs');

class InstagramScraper extends ScraperBase {
  getName() {
    return 'Instagram';
  }

  canHandle(url) {
    return url.includes('instagram.com');
  }

  async scrape(url, log, options = {}) {
    const { isCancelled = () => false } = options;
    let win = null;
    let cookieFilePath = path.join(app.getPath('userData'), 'instagram_cookies.txt');

    try {
      log(`[Instagram] Starting scrape for ${url}`);

      // 1. Create hidden window
      win = new BrowserWindow({
        show: false,
        width: 1200,
        height: 800,
        webPreferences: {
          partition: 'persist:instagram',
          nodeIntegration: false,
          contextIsolation: true
        }
      });

      // 2. Load the target URL directly
      // If it's a profile, we scroll and scrape.
      // If it's a post, we just grab it.
      await win.loadURL(url);

      // Verify if login is needed (simple check)
      const title = await win.getTitle();
      if (title.includes('Login')) {
         log(`[Instagram] Login page detected. Please login in the main browser window if functionality fails.`);
         // We could try to wait for user to login, but since it's hidden, we can't.
         // Ideally we rely on the persistent session.
      }
      
      // Save cookies for later yt-dlp usage
      try {
          const cookies = await win.webContents.session.cookies.get({});
          const netscapeCookies = cookies.map(cookie => {
            const domain = cookie.domain.startsWith('.') ? cookie.domain : `.${cookie.domain}`;
            const flag = 'TRUE'; 
            const path = cookie.path;
            const secure = cookie.secure ? 'TRUE' : 'FALSE';
            const expiration = Math.floor(cookie.expirationDate || (Date.now() / 1000 + 31536000));
            return `${domain}\t${flag}\t${path}\t${secure}\t${expiration}\t${cookie.name}\t${cookie.value}`;
          }).join('\n');
          const header = "# Netscape HTTP Cookie File\n# This file is generated by RedditGrabber\n\n";
          fs.writeFileSync(cookieFilePath, header + netscapeCookies);
      } catch (e) { log(`[Instagram] Failed to save cookies: ${e.message}`); }

      const isPost = url.includes('/p/') || url.includes('/reel/') || url.includes('/tv/');
      
      if (isPost) {
          log(`[Instagram] Detected single post.`);
          // Just return the job
          let id = 'unknown';
          const match = url.match(/\/(?:p|reel|tv)\/([^\/]+)/);
          if (match) id = match[1];
          return [{
            url: url,
            type: 'ytdlp',
            downloader: 'ytdlp',
            id: id,
            title: `instagram_${id}`,
            cookiePath: cookieFilePath,
            domain: 'instagram.com'
          }];
      }

      // PROFILE SCRAPING
      log(`[Instagram] Detected profile. Scrolling to find posts...`);
      
      // Extract username
      let username = 'instagram_profile';
      try {
        const urlObj = new URL(url);
        const parts = urlObj.pathname.split('/').filter(p => p.length > 0);
        if (parts.length > 0) username = parts[0];
      } catch(e) {}

      // Scroll and scrape loop
      const postLinks = new Set();
      let lastHeight = 0;
      let noChangeCount = 0;
      const MAX_NO_CHANGE = 3; // Stop after 3 checks with no new content
      const MAX_SCROLLS = 50; // Safety limit, maybe make configurable later

      for (let i = 0; i < MAX_SCROLLS; i++) {
        if (isCancelled()) break;

        // Scrape current view
        const found = await win.webContents.executeJavaScript(`
          (() => {
            const links = [];
            document.querySelectorAll('a').forEach(a => {
              const href = a.getAttribute('href');
              if (href && (href.startsWith('/p/') || href.startsWith('/reel/') || href.startsWith('/tv/'))) {
                 links.push(a.href);
              }
            });
            return links;
          })()
        `);

        let newFound = 0;
        for (const link of found) {
          if (!postLinks.has(link)) {
            postLinks.add(link);
            newFound++;
          }
        }
        
        log(`[Instagram] Scroll ${i+1}: Found ${found.length} links (${newFound} new). Total unique: ${postLinks.size}`);

        // Scroll down
        lastHeight = await win.webContents.executeJavaScript('document.body.scrollHeight');
        await win.webContents.executeJavaScript('window.scrollTo(0, document.body.scrollHeight);');
        
        // Wait for load
        await new Promise(r => setTimeout(r, 2000 + Math.random() * 1000));
        
        const newHeight = await win.webContents.executeJavaScript('document.body.scrollHeight');
        if (newHeight === lastHeight) {
            noChangeCount++;
            if (noChangeCount >= MAX_NO_CHANGE) {
                log(`[Instagram] Reached end of page (or stuck).`);
                break;
            }
        } else {
            noChangeCount = 0;
        }
      }

      const results = [];
      for (const link of postLinks) {
          let id = 'unknown';
          const match = link.match(/\/(?:p|reel|tv)\/([^\/]+)/);
          if (match) id = match[1];
          
          results.push({
            url: link,
            type: 'ytdlp',
            downloader: 'ytdlp', // Use generic downloader for the individual post
            id: id,
            title: `instagram_${username}_${id}`,
            seriesFolder: username,
            cookiePath: cookieFilePath,
            domain: 'instagram.com'
          });
      }

      log(`[Instagram] Finished. Found ${results.length} total media items.`);
      return results;

    } catch (error) {
      log(`[Instagram] Error: ${error.message}`);
      return [];
    } finally {
      if (win) win.destroy();
    }
  }
}

module.exports = InstagramScraper;
